services:
  day1:
    build: ./Day1_Ingest_and_index_your_data
    container_name: day1-ingest

  day2:
    build: ./Day2_Chunking_and_processing
    container_name: day2-chunking

  day3:
    build: ./Day3_Search
    container_name: day3-search

  day4:
    build: ./Day4_Agents
    container_name: day4-agents

  day5:
    build: ./Day5_Evaluation
    container_name: day5-evaluation
